using System.Collections.Concurrent;
using System.Management.Automation;

using PSFuzzySelect.UI.Renderer;
using PSFuzzySelect.UI.Components;
using PSFuzzySelect.UI.Styles;

namespace PSFuzzySelect.UI;

/// <summary>
/// Defines the contract for an interactive application that can be rendered on the console and can update its state based on user interactions.
/// </summary>
public interface IApplication : IComponent
{
    /// <summary>
    /// Updates the state of the application based on the received message.
    /// This method is called by the Engine to process user actions and internal notifications.
    /// </summary>
    /// <param name="message">The message representing an action or event.</param>
    /// <returns>A follow-up Message object to be processed in the same frame, or null if processing is complete.</returns>
    Message? Update(Message? message);
}

/// <summary>
/// The Engine class is responsible for managing the main loop of the fuzzy selector application,
/// including rendering the UI components, handling user input, and updating the state of the application based on user interactions.
/// </summary>
/// <param name="App">The root component of the application, which will be rendered and updated by the engine</param>
public class Engine(IApplication App)
{
    /// <summary>The renderer responsible for drawing the UI components of the fuzzy selector application on the console</summary>
    private readonly ConsoleRenderer _renderer = new(Console.WindowWidth, Console.WindowHeight);

    /// <summary>A flag indicating whether the fuzzy selector should quit</summary>
    private bool _shouldQuit = false;

    /// <summary>The background worker responsible for generating preview content asynchronously</summary>
    private PreviewWorker? _previewWorker;

    /// <summary>
    /// Performs initial setup for the console, such as hiding the cursor and entering the alternate screen buffer
    /// to prepare for rendering the UI components of the fuzzy selector application.
    /// </summary>
    private static void Setup()
    {
        Console.OutputEncoding = System.Text.Encoding.UTF8; // Ensure the console can render UTF-8 characters
        string ansi = string.Concat([
            Ansi.AltBufferEnter,      // Switch to the alternate screen buffer
            Ansi.CursorHide,          // Hide the cursor for a cleaner UI experience
            Ansi.ClearScreen,         // Ensure the alternate buffer is completely clear
            Ansi.CursorPosition(0, 0) // Reset cursor to the top-left corner
        ]);
        Console.Write(ansi);          // Write the ANSI escape codes to the console to apply the setup
    }

    /// <summary>
    /// Runs the main loop of the fuzzy selector application: render, collect events, process messages.
    /// </summary>
    public void Run()
    {
        Setup();

        try
        {
            while (!_shouldQuit)
            {
                Render();

                // Collect all pending events, then process them before the next render
                foreach (var message in CollectEvents())
                {
                    if (_shouldQuit) break;
                    ProcessMessage(message);
                }
            }
        }
        finally
        {
            Cleanup();
        }
    }

    /// <summary>
    /// Shows the fuzzy selector UI for the provided collection of items and returns the selected item based on user interaction.
    /// </summary>
    public static object? Show(
        string prompt,
        IEnumerable<object> items,
        string[]? properties = null,
        bool multiSelect = false,
        bool showPreview = false,
        string previewSize = "50%",
        PreviewPosition previewPosition = PreviewPosition.Right,
        ScriptBlock? previewScript = null
    )
    {
        var selector = new FuzzySelector(prompt, items, properties, multiSelect, showPreview, previewSize, previewPosition);
        var engine = new Engine(selector);
        try
        {
            if (showPreview && previewScript != null)
            {
                engine._previewWorker = new PreviewWorker(previewScript, msg => engine.EnqueueMessage(msg));

                // Prime preview generation so it updates even before the first key press.
                var initialPreview = selector.CreateInitialPreviewRequest();
                if (initialPreview != null)
                {
                    engine.ProcessMessage(initialPreview);
                }
            }

            // Run the main loop of the fuzzy selector
            engine.Run();

            // Return the selected value after the user has made a selection
            return selector.SelectedValue;
        }
        finally
        {
            engine._previewWorker?.Dispose();
        }
    }

    /// <summary>
    /// A thread-safe queue to hold messages generated by user input or internal events that need to be processed by the main loop.
    /// </summary>
    private readonly ConcurrentQueue<Message> _messageQueue = new();

    /// <summary>
    /// Enqueues a message to be processed by the main loop. This method can be called from any thread to safely add messages to the queue,
    /// which will then be processed in the next iteration of the main loop after rendering.
    /// </summary>
    /// <param name="message">The message to enqueue</param>
    public void EnqueueMessage(Message message)
    {
        _messageQueue.Enqueue(message);
    }

    #region Event Collection

    /// <summary>
    /// Collects all pending events: blocks until at least one event is available,
    /// then drains any additional queued messages and buffered keystrokes.
    /// </summary>
    private List<Message> CollectEvents()
    {
        var events = new List<Message>();

        // Block until at least one event is available
        events.Add(WaitForEvent());

        // Drain any queued messages (e.g. from PreviewWorker)
        while (_messageQueue.TryDequeue(out var queued))
            events.Add(queued);

        // Drain any buffered keystrokes
        while (Console.KeyAvailable)
            events.Add(new KeyEvent(Console.ReadKey(intercept: true)));

        return events;
    }

    /// <summary>
    /// Blocks until a single event is available from the message queue, a console resize, or a keystroke.
    /// </summary>
    private Message WaitForEvent()
    {
        while (true)
        {
            if (_messageQueue.TryDequeue(out var queued))
                return queued;

            if (Console.WindowWidth != _renderer.Width || Console.WindowHeight != _renderer.Height)
                return new Resize(Console.WindowWidth, Console.WindowHeight);

            if (Console.KeyAvailable)
                return new KeyEvent(Console.ReadKey(intercept: true));

            Thread.Sleep(16); // Avoid busy-waiting
        }
    }

    #endregion Event Collection

    #region Message Processing

    /// <summary>
    /// Processes a single message and its follow-up chain. Each message passes through
    /// three stages: engine pre-processing, app dispatch, and engine side-effects.
    /// </summary>
    private void ProcessMessage(Message message)
    {
        Message? current = message;
        while (current != null && !_shouldQuit)
        {
            // 1. Engine pre-processing: handle messages the engine owns (Resize, Quit)
            current = HandleEngineMessage(current);
            if (current == null) break;

            // 2. App dispatch: let the application process the message and return a follow-up
            current = App.Update(current);

            // 3. Engine side-effects: intercept follow-up messages meant for the engine (RequestPreview)
            current = HandleSideEffects(current);
        }
    }

    /// <summary>
    /// Handles messages that are engine-level concerns.
    /// Returns null if the message was fully consumed, or the message itself to continue to the app.
    /// </summary>
    private Message? HandleEngineMessage(Message message)
    {
        switch (message)
        {
            case Resize r:
                _renderer.Resize(r.Width, r.Height);
                return message; // Also pass to app so it can re-layout
            case Quit:
                _shouldQuit = true;
                return null; // Consumed — stop the chain
            default:
                return message; // Pass through to app
        }
    }

    /// <summary>
    /// Intercepts follow-up messages returned by the app that represent engine-level side effects.
    /// Returns null if consumed, or the message to continue the follow-up chain.
    /// </summary>
    private Message? HandleSideEffects(Message? message)
    {
        switch (message)
        {
            case RequestPreview { Item: not null } rp:
                _previewWorker?.Enqueue(rp.Item);
                return null; // Consumed — dispatched to worker
            case RequestPreview: // Item is null — clear the preview
                App.Update(new UpdatePreview(string.Empty));
                return null; // Consumed
            default:
                return message; // Continue the follow-up chain
        }
    }

    #endregion Message Processing

    /// <summary>
    /// Renders the entire UI by delegating to the root component, which will recursively render
    /// itself and its child components onto the renderer's back buffer, and then instructing the renderer to draw the buffer to the console.
    /// This method is called on each iteration of the main loop to update the display based on the current state of the UI components.
    /// </summary>
    private void Render()
    {
        var buffer = _renderer.GetBackBuffer();     // Get a fresh buffer for rendering the current frame
        App.Render(buffer);                        // Render the root component (and its children) to the buffer surface
        _renderer.Render();                         // Render the current buffer to the console
    }

    /// <summary>
    /// Cleans up the console UI by making the cursor visible, resetting the console colors, and exiting the alternate screen buffer.
    /// </summary>
    private static void Cleanup()
    {
        string ansi = string.Concat([
             Ansi.Reset,          // Reset console colors and styles to default
             Ansi.CursorShow,     // Ensure the cursor is visible again when exiting
             Ansi.AltBufferExit   // Switch back to the main screen buffer, restoring the previous screen state
        ]);
        Console.Write(ansi);      // Write the ANSI escape codes to the console to apply the cleanup
    }

}
